FROM node:14

# Create App Directory
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

# Install Dependencies
COPY package*.json ./

RUN npm install
RUN npm install -g nodemon

# Copy app source code
COPY . .

# Exports
EXPOSE 8080

CMD ["npm","run","dev"]